### ISSUE TITLE
Expose interfaces in DataTable/types to allow better component customisation

### ISSUE THREAD

**Issue by gc-6point6** [gilbarbara/components#37]
DataTable comes with limited customisation options. 
Enabling developers to implement the interfaces defined in DataTable/types would allow better component customisations. 

e.g.

```
const data = useMemo(
    () =>
      results.map(package_ => {
        const row: DataTableRow<ExternalColumns> = {
          id: package_.name,
          name: package_.name,
          description: package_.description,
          keywords: package_.keywords ? package_.keywords.join(', ') : '--',
          version: {
            label: <Tag bg={accent}>{package_.version}</Tag>,
            value: package_.version,
          },
          links: (
            <>
              <Anchor color={accent} href={package_.links.homepage} target="_blank">
                Homepage
              </Anchor>
              <Anchor color={accent} href={package_.links.npm} target="_blank">
                NPM
              </Anchor>
            </>
          ),
        };

        return row;
      }),
    [accent, results],
  );
```

This is not possible because DataTableRow is not publicly exposed.

**Comment by gilbarbara** [comment]
Hey @gc-6point6 

It is under the `Props` namespace.
`Props.DataTableRow`

**Comment by gilbarbara** [comment]
I forgot to add that to the README. I'm going to update it.

**Comment by gc-6point6** [comment]
Thanks a lot!

**Comment by gc-6point6** [comment]
> I forgot to add that to the README. I'm going to update it.

Could you show me how to access Props.DataTableRow? 
Checked the exports, "as DataTableRow" ... not sure why I can't access it under Props. 

Thanks.

**Comment by gilbarbara** [comment]
Hey @gc-6point6 

What version are you using?
And can you post a simple example of what you're trying to do and what the problem is?
You normally don't need to access the DataTableRow directly. Check the DataTable [story](https://github.com/gilbarbara/components/blob/main/src/components/DataTable/DataTable.stories.tsx) for an example.

```tsx
import { Props } from '@gilbarbara/components';

interface Props {
	someKey?: Props.DataTableRow['someOtherKey'];
}

// or

interface Props extends Props.DataTableRow {
	...
}
```

**Comment by gc-6point6** [comment]
Hi @gilbarbara , 

thanks for the the reply. 
Resuming work on this project now .

I got it working in the end:

`import { Button, DataTable, Icon, Jumbo, Page, Props, Spacer,  } from '@gilbarbara/components';`

and then 

`const rows: Props.DataTableRow<Columns>[] = [`

Thanks.
